# env config
sample:
  # 名称
  name: ddd-sample
  # 版本
  version: 0.0.1

server:
  # 端口
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # URI编码
    uri-encoding: UTF-8
    # 最大线程数，默认为200
    max-threads: 800
    # 启动初始化的线程数，默认值25
    min-spare-threads: 30

logging:
  level:
    com.twinfrozr: debug
    org.springframework: warn

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true